import type { MarketStats, OfferListItem } from "./types";

function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * 60 * 1000).toISOString();
}

const MOCK_OFFERS: OfferListItem[] = [
  {
    id: "offer-1",
    supplierId: "supplier-al-hadi",
    supplierName: "Al Hadi Computers LLC",
    supplierVerified: true,
    supplierSlug: "al-hadi-computers",
    supplierPositiveScorePercent: 98,
    brandId: "brand-lenovo",
    brandName: "Lenovo",
    categoryId: "cat-laptops",
    categoryName: "Laptops",
    locationName: "Bur Dubai",
    title: "Lenovo ThinkPad E14 Gen 7",
    specLine: ["Intel Core Ultra 7 155H", "16GB RAM", "512GB SSD", '14" FHD', "Win 11 Pro"],
    quantity: 120,
    price: 3850,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: "NEW",
    postedAt: minutesAgo(2),
    whatsappNumber: "+971543210001",
  },
  {
    id: "offer-2",
    supplierId: "supplier-skyline",
    supplierName: "Skyline General Trading",
    supplierVerified: true,
    supplierSlug: "skyline-general-trading",
    supplierPositiveScorePercent: 97,
    brandId: "brand-hp",
    brandName: "HP",
    categoryId: "cat-laptops",
    categoryName: "Laptops",
    locationName: "Bur Dubai",
    title: "HP 250 G10",
    specLine: ["Intel Core i5-1335U", "8GB RAM", "512GB SSD", '15.6" FHD', "DOS"],
    quantity: 70,
    price: null,
    currency: "AED",
    priceType: "ASK",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: "LIVE",
    postedAt: minutesAgo(8),
    whatsappNumber: "+971543210002",
  },
  {
    id: "offer-3",
    supplierId: "supplier-microlink",
    supplierName: "Microlink Technology LLC",
    supplierVerified: true,
    supplierSlug: "microlink-technology",
    supplierPositiveScorePercent: 99,
    brandId: "brand-wd",
    brandName: "WD",
    categoryId: "cat-storage",
    categoryName: "Storage",
    locationName: "Bur Dubai",
    title: "WD Purple 8TB Surveillance HDD",
    specLine: ['3.5"', "SATA III", "256MB Cache", "For CCTV", "WD82PURZ"],
    quantity: 50,
    price: 540,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: 570,
    availabilityStatus: "AVAILABLE",
    badge: "PRICE_UPDATED",
    postedAt: minutesAgo(12),
    whatsappNumber: "+971543210003",
  },
  {
    id: "offer-4",
    supplierId: "supplier-network-zone",
    supplierName: "Network Zone FZE",
    supplierVerified: true,
    supplierSlug: "network-zone",
    supplierPositiveScorePercent: 98,
    brandId: "brand-aruba",
    brandName: "Aruba",
    categoryId: "cat-networking",
    categoryName: "Networking",
    locationName: "Al Fahidi",
    title: "Aruba Instant On AP25 (R9B28A)",
    specLine: ["Wi-Fi 6", "Dual Band", "2x2:2 MIMO", "PoE", "Indoor Access Point"],
    quantity: 20,
    price: null,
    currency: "AED",
    priceType: "ASK",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: "LIVE",
    postedAt: minutesAgo(18),
    whatsappNumber: "+971543210004",
  },
  {
    id: "offer-5",
    supplierId: "supplier-techno-source",
    supplierName: "Techno Source LLC",
    supplierVerified: true,
    supplierSlug: "techno-source",
    supplierPositiveScorePercent: 96,
    brandId: "brand-dell",
    brandName: "Dell",
    categoryId: "cat-desktops",
    categoryName: "Desktops",
    locationName: "Bur Dubai",
    title: "Dell OptiPlex 7020 SFF",
    specLine: ["Intel Core i7-14700", "16GB RAM", "512GB SSD", "Intel UHD", "Win 11 Pro"],
    quantity: 40,
    price: 2950,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: "LIVE",
    postedAt: minutesAgo(25),
    whatsappNumber: "+971543210005",
  },
  {
    id: "offer-6",
    supplierId: "supplier-seven-seas",
    supplierName: "Seven Seas Computers",
    supplierVerified: true,
    supplierSlug: "seven-seas-computers",
    supplierPositiveScorePercent: 99,
    brandId: "brand-apple",
    brandName: "Apple",
    categoryId: "cat-laptops",
    categoryName: "Laptops",
    locationName: "Deira",
    title: 'Apple MacBook Air 13" M3',
    specLine: ["Apple M3", "16GB RAM", "512GB SSD", '13.6" Liquid Retina', "macOS"],
    quantity: 15,
    price: 4650,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: "NEW",
    postedAt: minutesAgo(32),
    whatsappNumber: "+971543210006",
  },
];

const MOCK_MARKET_STATS: MarketStats = {
  activeSuppliersToday: 342,
  activeSuppliersTrendPercent: 12,
  offersPostedToday: 1284,
  offersPostedTrendPercent: 28,
  priceUpdatesToday: 756,
  priceUpdatesTrendPercent: 19,
  newProductsToday: 210,
  newProductsTrendPercent: 32,
};

export function getMockOffers(): OfferListItem[] {
  return MOCK_OFFERS;
}

export function getMockMarketStats(): MarketStats {
  return MOCK_MARKET_STATS;
}
