import type {
  CategoryPriceMovement,
  MarketStats,
  OfferListItem,
  TrendingSearchTerm,
  WtbRequestSnippet,
} from "./types";

function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * 60 * 1000).toISOString();
}

const MOCK_OFFERS: OfferListItem[] = [
  {
    id: "offer-1",
    supplierId: "supplier-al-hadi",
    supplierName: "Al Hadi Computers LLC",
    supplierVerified: true,
    supplierSlug: "al-hadi-computers",
    supplierPositiveScorePercent: 98,
    brandId: "brand-lenovo",
    brandName: "Lenovo",
    categoryId: "cat-laptops",
    categoryName: "Laptops",
    locationName: "Bur Dubai",
    title: "Lenovo ThinkPad E14 Gen 7",
    specLine: [
      "Intel Core Ultra 7 155H",
      "16GB RAM",
      "512GB SSD",
      '14" FHD',
      "Win 11 Pro",
    ],
    quantity: 120,
    price: 3850,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: "NEW",
    postedAt: minutesAgo(2),
    whatsappNumber: "+971543210001",
  },
  {
    id: "offer-2",
    supplierId: "supplier-skyline",
    supplierName: "Skyline General Trading",
    supplierVerified: true,
    supplierSlug: "skyline-general-trading",
    supplierPositiveScorePercent: 97,
    brandId: "brand-hp",
    brandName: "HP",
    categoryId: "cat-laptops",
    categoryName: "Laptops",
    locationName: "Bur Dubai",
    title: "HP 250 G10",
    specLine: [
      "Intel Core i5-1335U",
      "8GB RAM",
      "512GB SSD",
      '15.6" FHD',
      "DOS",
    ],
    quantity: 70,
    price: null,
    currency: "AED",
    priceType: "ASK",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: "LIVE",
    postedAt: minutesAgo(8),
    whatsappNumber: "+971543210002",
  },
  {
    id: "offer-3",
    supplierId: "supplier-microlink",
    supplierName: "Microlink Technology LLC",
    supplierVerified: true,
    supplierSlug: "microlink-technology",
    supplierPositiveScorePercent: 99,
    brandId: "brand-wd",
    brandName: "WD",
    categoryId: "cat-storage",
    categoryName: "Storage",
    locationName: "Bur Dubai",
    title: "WD Purple 8TB Surveillance HDD",
    specLine: ['3.5"', "SATA III", "256MB Cache", "For CCTV", "WD82PURZ"],
    quantity: 50,
    price: 540,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: 570,
    availabilityStatus: "AVAILABLE",
    badge: "PRICE_UPDATED",
    postedAt: minutesAgo(12),
    whatsappNumber: "+971543210003",
  },
  {
    id: "offer-4",
    supplierId: "supplier-network-zone",
    supplierName: "Network Zone FZE",
    supplierVerified: true,
    supplierSlug: "network-zone",
    supplierPositiveScorePercent: 98,
    brandId: "brand-aruba",
    brandName: "Aruba",
    categoryId: "cat-networking",
    categoryName: "Networking",
    locationName: "Al Fahidi",
    title: "Aruba Instant On AP25 (R9B28A)",
    specLine: [
      "Wi-Fi 6",
      "Dual Band",
      "2x2:2 MIMO",
      "PoE",
      "Indoor Access Point",
    ],
    quantity: 20,
    price: null,
    currency: "AED",
    priceType: "ASK",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: "LIVE",
    postedAt: minutesAgo(18),
    whatsappNumber: "+971543210004",
  },
  {
    id: "offer-5",
    supplierId: "supplier-techno-source",
    supplierName: "Techno Source LLC",
    supplierVerified: true,
    supplierSlug: "techno-source",
    supplierPositiveScorePercent: 96,
    brandId: "brand-dell",
    brandName: "Dell",
    categoryId: "cat-desktops",
    categoryName: "Desktops",
    locationName: "Bur Dubai",
    title: "Dell OptiPlex 7020 SFF",
    specLine: [
      "Intel Core i7-14700",
      "16GB RAM",
      "512GB SSD",
      "Intel UHD",
      "Win 11 Pro",
    ],
    quantity: 40,
    price: 2950,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: "LIVE",
    postedAt: minutesAgo(25),
    whatsappNumber: "+971543210005",
  },
  {
    id: "offer-6",
    supplierId: "supplier-seven-seas",
    supplierName: "Seven Seas Computers",
    supplierVerified: true,
    supplierSlug: "seven-seas-computers",
    supplierPositiveScorePercent: 99,
    brandId: "brand-apple",
    brandName: "Apple",
    categoryId: "cat-laptops",
    categoryName: "Laptops",
    locationName: "Deira",
    title: 'Apple MacBook Air 13" M3',
    specLine: [
      "Apple M3",
      "16GB RAM",
      "512GB SSD",
      '13.6" Liquid Retina',
      "macOS",
    ],
    quantity: 15,
    price: 4650,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: "NEW",
    postedAt: minutesAgo(32),
    whatsappNumber: "+971543210006",
  },
  {
    id: "offer-7",
    supplierId: "supplier-al-hadi",
    supplierName: "Al Hadi Computers LLC",
    supplierVerified: true,
    supplierSlug: "al-hadi-computers",
    supplierPositiveScorePercent: 98,
    brandId: "brand-lenovo",
    brandName: "Lenovo",
    categoryId: "cat-desktops",
    categoryName: "Desktops",
    locationName: "Bur Dubai",
    title: "Lenovo ThinkCentre M70s Gen 4",
    specLine: [
      "Intel Core i5-13500",
      "8GB RAM",
      "256GB SSD",
      "Intel UHD 770",
      "Win 11 Pro",
    ],
    quantity: 45,
    price: 2150,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: "LIVE",
    postedAt: minutesAgo(4),
    whatsappNumber: "+971543210007",
  },
  {
    id: "offer-8",
    supplierId: "supplier-seven-seas",
    supplierName: "Seven Seas Computers",
    supplierVerified: true,
    supplierSlug: "seven-seas-computers",
    supplierPositiveScorePercent: 99,
    brandId: "brand-apple",
    brandName: "Apple",
    categoryId: "cat-laptops",
    categoryName: "Laptops",
    locationName: "Deira",
    title: 'Apple MacBook Pro 14" M3 Pro',
    specLine: [
      "Apple M3 Pro",
      "18GB RAM",
      "512GB SSD",
      '14.2" Liquid Retina XDR',
      "macOS",
    ],
    quantity: 6,
    price: null,
    currency: "AED",
    priceType: "ASK",
    previousPrice: null,
    availabilityStatus: "LIMITED",
    badge: "NEW",
    postedAt: minutesAgo(3),
    whatsappNumber: "+971543210008",
  },
  {
    id: "offer-9",
    supplierId: "supplier-techno-source",
    supplierName: "Techno Source LLC",
    supplierVerified: true,
    supplierSlug: "techno-source",
    supplierPositiveScorePercent: 96,
    brandId: "brand-dell",
    brandName: "Dell",
    categoryId: "cat-laptops",
    categoryName: "Laptops",
    locationName: "Bur Dubai",
    title: "Dell Latitude 5440",
    specLine: [
      "Intel Core i5-1335U",
      "16GB RAM",
      "256GB SSD",
      '14" FHD',
      "Win 11 Pro",
    ],
    quantity: 60,
    price: 3200,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: null,
    postedAt: minutesAgo(10),
    whatsappNumber: "+971543210009",
  },
  {
    id: "offer-10",
    supplierId: "supplier-al-hadi",
    supplierName: "Al Hadi Computers LLC",
    supplierVerified: true,
    supplierSlug: "al-hadi-computers",
    supplierPositiveScorePercent: 98,
    brandId: "brand-hp",
    brandName: "HP",
    categoryId: "cat-accessories",
    categoryName: "Accessories",
    locationName: "Bur Dubai",
    title: "HP LaserJet Pro M404dn",
    specLine: [
      "Monochrome Laser",
      "38ppm",
      "Duplex Printing",
      "USB + Ethernet",
    ],
    quantity: 25,
    price: 650,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: null,
    postedAt: minutesAgo(14),
    whatsappNumber: "+971543210010",
  },
  {
    id: "offer-11",
    supplierId: "supplier-microlink",
    supplierName: "Microlink Technology LLC",
    supplierVerified: true,
    supplierSlug: "microlink-technology",
    supplierPositiveScorePercent: 99,
    brandId: "brand-wd",
    brandName: "WD",
    categoryId: "cat-storage",
    categoryName: "Storage",
    locationName: "Bur Dubai",
    title: "WD Blue 2TB SATA SSD",
    specLine: ['2.5"', "SATA III", "560MB/s Read", "5Y Warranty"],
    quantity: 90,
    price: 285,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: 310,
    availabilityStatus: "AVAILABLE",
    badge: "PRICE_UPDATED",
    postedAt: minutesAgo(6),
    whatsappNumber: "+971543210011",
  },
  {
    id: "offer-12",
    supplierId: "supplier-network-zone",
    supplierName: "Network Zone FZE",
    supplierVerified: true,
    supplierSlug: "network-zone",
    supplierPositiveScorePercent: 98,
    brandId: "brand-aruba",
    brandName: "Aruba",
    categoryId: "cat-networking",
    categoryName: "Networking",
    locationName: "Al Fahidi",
    title: "Aruba 2930F 24G PoE+ Switch (JL262A)",
    specLine: ["24-Port Gigabit", "4x SFP+", "PoE+ 740W", "L3 Lite"],
    quantity: 12,
    price: null,
    currency: "AED",
    priceType: "ASK",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: "LIVE",
    postedAt: minutesAgo(9),
    whatsappNumber: "+971543210012",
  },
  {
    id: "offer-13",
    supplierId: "supplier-skyline",
    supplierName: "Skyline General Trading",
    supplierVerified: true,
    supplierSlug: "skyline-general-trading",
    supplierPositiveScorePercent: 97,
    brandId: "brand-acer",
    brandName: "Acer",
    categoryId: "cat-laptops",
    categoryName: "Laptops",
    locationName: "Bur Dubai",
    title: "Acer Aspire 7 A715",
    specLine: [
      "AMD Ryzen 5 7435HS",
      "16GB RAM",
      "512GB SSD",
      '15.6" FHD 144Hz',
      "Win 11",
    ],
    quantity: 35,
    price: 2450,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: null,
    postedAt: minutesAgo(19),
    whatsappNumber: "+971543210013",
  },
  {
    id: "offer-14",
    supplierId: "supplier-techno-source",
    supplierName: "Techno Source LLC",
    supplierVerified: true,
    supplierSlug: "techno-source",
    supplierPositiveScorePercent: 96,
    brandId: "brand-dell",
    brandName: "Dell",
    categoryId: "cat-desktops",
    categoryName: "Desktops",
    locationName: "Bur Dubai",
    title: "Dell OptiPlex 3000 Micro",
    specLine: [
      "Intel Core i5-13500T",
      "8GB RAM",
      "256GB SSD",
      "Intel UHD",
      "Win 11 Pro",
    ],
    quantity: 55,
    price: 1950,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: "NEW",
    postedAt: minutesAgo(2),
    whatsappNumber: "+971543210014",
  },
  {
    id: "offer-15",
    supplierId: "supplier-al-hadi",
    supplierName: "Al Hadi Computers LLC",
    supplierVerified: true,
    supplierSlug: "al-hadi-computers",
    supplierPositiveScorePercent: 98,
    brandId: "brand-samsung",
    brandName: "Samsung",
    categoryId: "cat-monitors",
    categoryName: "Monitors",
    locationName: "Bur Dubai",
    title: 'Samsung 27" Odyssey G5 Curved',
    specLine: ['27" QHD 165Hz', "1ms MPRT", "VA Panel", "FreeSync Premium"],
    quantity: 20,
    price: 899,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: null,
    postedAt: minutesAgo(27),
    whatsappNumber: "+971543210015",
  },
  {
    id: "offer-16",
    supplierId: "supplier-microlink",
    supplierName: "Microlink Technology LLC",
    supplierVerified: true,
    supplierSlug: "microlink-technology",
    supplierPositiveScorePercent: 99,
    brandId: "brand-samsung",
    brandName: "Samsung",
    categoryId: "cat-storage",
    categoryName: "Storage",
    locationName: "Bur Dubai",
    title: "Samsung 990 PRO 2TB NVMe SSD",
    specLine: ["PCIe 4.0 x4", "7450MB/s Read", "V-NAND", "5Y Warranty"],
    quantity: 48,
    price: 580,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: 640,
    availabilityStatus: "AVAILABLE",
    badge: "PRICE_UPDATED",
    postedAt: minutesAgo(7),
    whatsappNumber: "+971543210016",
  },
  {
    id: "offer-17",
    supplierId: "supplier-network-zone",
    supplierName: "Network Zone FZE",
    supplierVerified: true,
    supplierSlug: "network-zone",
    supplierPositiveScorePercent: 98,
    brandId: "brand-cisco",
    brandName: "Cisco",
    categoryId: "cat-networking",
    categoryName: "Networking",
    locationName: "Al Fahidi",
    title: "Cisco Catalyst 1000 24P Switch",
    specLine: ["24x GigE", "4x SFP", "L2 Managed", "Rack Mountable"],
    quantity: 9,
    price: null,
    currency: "AED",
    priceType: "ASK",
    previousPrice: null,
    availabilityStatus: "LIMITED",
    badge: "LIVE",
    postedAt: minutesAgo(11),
    whatsappNumber: "+971543210017",
  },
  {
    id: "offer-18",
    supplierId: "supplier-seven-seas",
    supplierName: "Seven Seas Computers",
    supplierVerified: true,
    supplierSlug: "seven-seas-computers",
    supplierPositiveScorePercent: 99,
    brandId: "brand-apple",
    brandName: "Apple",
    categoryId: "cat-accessories",
    categoryName: "Accessories",
    locationName: "Deira",
    title: "Apple Magic Keyboard + Magic Mouse Combo",
    specLine: ["Wireless", "USB-C Rechargeable", "Arabic/English Layout"],
    quantity: 40,
    price: 420,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: null,
    postedAt: minutesAgo(33),
    whatsappNumber: "+971543210018",
  },
  {
    id: "offer-19",
    supplierId: "supplier-skyline",
    supplierName: "Skyline General Trading",
    supplierVerified: true,
    supplierSlug: "skyline-general-trading",
    supplierPositiveScorePercent: 97,
    brandId: "brand-logitech",
    brandName: "Logitech",
    categoryId: "cat-accessories",
    categoryName: "Accessories",
    locationName: "Bur Dubai",
    title: "Logitech MX Master 3S",
    specLine: [
      "8K DPI Sensor",
      "Quiet Clicks",
      "USB-C",
      "Bluetooth + Receiver",
    ],
    quantity: 60,
    price: 285,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: "NEW",
    postedAt: minutesAgo(1),
    whatsappNumber: "+971543210019",
  },
  {
    id: "offer-20",
    supplierId: "supplier-techno-source",
    supplierName: "Techno Source LLC",
    supplierVerified: true,
    supplierSlug: "techno-source",
    supplierPositiveScorePercent: 96,
    brandId: "brand-lenovo",
    brandName: "Lenovo",
    categoryId: "cat-components",
    categoryName: "Components",
    locationName: "Bur Dubai",
    title: "Lenovo 16GB DDR5 5600MHz SO-DIMM",
    specLine: ["Laptop RAM", "DDR5-5600", "CL46", "1.1V"],
    quantity: 150,
    price: 195,
    currency: "AED",
    priceType: "FIXED",
    previousPrice: null,
    availabilityStatus: "AVAILABLE",
    badge: null,
    postedAt: minutesAgo(24),
    whatsappNumber: "+971543210020",
  },
];

const MOCK_MARKET_STATS: MarketStats = {
  activeSuppliersToday: 342,
  activeSuppliersTrendPercent: 12,
  offersPostedToday: 1284,
  offersPostedTrendPercent: 28,
  priceUpdatesToday: 756,
  priceUpdatesTrendPercent: 19,
  newProductsToday: 210,
  newProductsTrendPercent: 32,
};

export function getMockOffers(): OfferListItem[] {
  return MOCK_OFFERS;
}

export function getMockMarketStats(): MarketStats {
  return MOCK_MARKET_STATS;
}

const MOCK_PRICE_MOVEMENTS: CategoryPriceMovement[] = [
  { categoryId: "cat-laptops", categoryName: "Laptops", changePercent: 24 },
  { categoryId: "cat-storage", categoryName: "Storage", changePercent: 18 },
  {
    categoryId: "cat-networking",
    categoryName: "Networking",
    changePercent: 32,
  },
  { categoryId: "cat-desktops", categoryName: "Desktops", changePercent: 12 },
  { categoryId: "cat-monitors", categoryName: "Monitors", changePercent: 9 },
];

const MOCK_TRENDING_SEARCHES: TrendingSearchTerm[] = [
  { term: "iPhone 15", searchCount: 248 },
  { term: "RTX 4090", searchCount: 197 },
  { term: "Lenovo ThinkPad", searchCount: 186 },
  { term: "HP 250 G10", searchCount: 162 },
  { term: "WD 8TB", searchCount: 148 },
];

const MOCK_WTB_REQUESTS: WtbRequestSnippet[] = [
  {
    id: "wtb-1",
    title: "WTB iPhone 15 Pro Max 256GB",
    location: "Dubai",
    postedLabel: "5m ago",
  },
  {
    id: "wtb-2",
    title: "WTB RTX 4080 / 4090",
    location: "Urgent",
    postedLabel: "12m ago",
  },
  {
    id: "wtb-3",
    title: "WTB Cisco Switches",
    location: "Dubai",
    postedLabel: "28m ago",
  },
  {
    id: "wtb-4",
    title: "WTB Dell Laptops (i7)",
    location: "Corporate",
    postedLabel: "41m ago",
  },
];

export function getMockPriceMovements(): CategoryPriceMovement[] {
  return MOCK_PRICE_MOVEMENTS;
}

export function getMockTrendingSearches(): TrendingSearchTerm[] {
  return MOCK_TRENDING_SEARCHES;
}

export function getMockWtbRequests(): WtbRequestSnippet[] {
  return MOCK_WTB_REQUESTS;
}
